apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation-dep
  namespace: graduation-documentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graduation-documentation
  template:
    metadata:
      labels:
        app: graduation-documentation
    spec:
      containers:
        - name: graduation-documentation
          image: ghcr.io/dan9191/graduation-work/docs:69bc67d4ff0769e86fe1fb0fb58090dade6255f3
          ports:
            - containerPort: 80
