apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/argoproj-labs/argocd-image-updater.git/config/default?ref=v1.1.0

patches:
  - target:
      kind: Deployment
      name: argocd-image-updater-controller
    patch: |-
      spec:
        template:
          spec:
            containers:
              - name: manager
                args:
                  - --annotation-mode=true
                  - --metrics-bind-address=:8443