---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-pass-secret
  namespace: observer
spec:
  encryptedData:
    postgres-password: AgBEUcG48DhNTAHy/TSRyNAExxvVKZzutoFa3gIXEup9NyjxWptqSSLuG0iAoo80nklV49JcOf5oFnk1VMa0H7Zn3tvK1V4T8zsj2a8avLBhq5B3iNjQDYm0AunC3GIEmN5DGwcZ69azLKYz+rHxuLwDcgKjkcP8/rckw16RkFIVx4GtA/YR0p2JASkhd0/iaGJ7RzJQHJm9vNyhdHQbcituF5RjMGCnLH3Wk4PW7UyPhFhxOprfm57ebvh/ELTOXJitLt1VEWPeBnWeqmTIVg5UQI0vzb8eu7uY5beFsVZcQtIwy3xDxL5bXAFEaHKPLb52mHB8F28ydVYN9yZkl2E+COMNByzJ7/hBR6QHrcRmdD1S3ACjnKNUK9EMVXdENlExy8j9OCaNcDMLuT5ZT4bFLh0zBC6wJy4OqgVeoePgX0+oibMCXi/JCm2Z5KFV2JKQLVJo7zZ1k7XPGoVs4Ffa0WKyHrHq3fv/TvoOwTmVmV/EWcauTdTy1UWdcNCT/tgHTXPTjG1gJ6+3BJV9PwXhZeIgq/5OYHV22hfhuQiYsG+JAtEC32o7yxop4JLvlkGXnSexhgrqgXnzKxxn+aDpYKsp50k+dk32J7aPAOjNZp+jDU1EUOmrMP1OG649ZZphYulDUwXcCBMDDROlMgzQhx42ChuJWaIjgOMfyt7UIwuN6vxCECeiH3eXV+/PsjzDBWIVxVG6TWkn6h4=
  template:
    metadata:
      name: postgres-pass-secret
      namespace: observer
