---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: keycloak
spec:
  encryptedData:
    postgres-password: AgBWCJZeGIYyQASv4P14oQ9ULbW4fryKMaoNr0QiforBPCBRlwbUJZbVqvZ0FnZhpRVXgI6WHSU5wRbaJKBYeYlV2FSj27Qn7ESkVx/uGBOZCdE1IP07mYXYeCFhpkWhTlMIQ5eaTJ1yFGWG4hyn5SkYB8v5gqV73NW0cnGV7aDbrVXtFx6Q7W5k2Kt2vyawLfo8d6hbCv+04Mw35n5RwIadmBntvnHGsMz5DaZrPw7Ps4EmoXF0cHdWY4R+HJuGkooMRiF6Lvcn/PCEBIfYLE5migS6qRUCdD+z8YGmUNY9BD1H9gkQlIyEnEvaMKPCRGOITO9LVZYtRqkxTLYvodJGRA4SZ+zWwmYnUApcC3x74Q82swrGKtvdudhnsqlDf3wT49prrq/xWSbJU/334c7iztD9qzxqDKbYZkyt71sEuzmhRDvq4PQTGJXrXdGmh3mTNSfKI6g6n/TYPpiV/n2P6jTw1IgQcm3wZMLmKSB8CLznPk2aCCjWt1+40DkOP0Dg296hlEV8KzmRfoB1alYMbBOYcgbaZFeshh74c+ixlj89sU0O9g6zpG0xSGDqKeVSXG1rfBnvfcmq4SEDE0DMPVMjd8O21o949nBc+TnP+G3ahiOSEm9yKC0pt1E7AtxZPsQcAdFUUzjjXh+hrRc2nvV15edyR6aDfY5FQ34dQ1WBCAbtQBxBcTW4U9BwkmUHs4qsD4q61h/Se5o=
  template:
    metadata:
      name: postgres-secret
      namespace: keycloak
