---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgB4tYCrFc/lCjKm35H4wNDfwtgfF+NfnDulQ6Q3Jue91XVfzBd1DShzFvojzqRaebzBmIgnVZkDbx27QVxMJ4a9gyL5OilY0Ys+h60ev9sSsUzPD2/QCo+g/wR0M5HcsyIhSgXe2sjWIOOI+A0Eqe4ZodcbGvRLRweBYg846seFtJIdY+PS+bsafgIy5eCl4mjTh+66bDTnilDtQT+mQwz0WKZaveLKB88Rd1mzA9ve9Ej8EezxRRq2+kt4149qdU76K1jAqOruT3eEb8jO0U2f4TF95Y8f4zRz+aym2t6bhJ8R97SEG5UnSl0CWdT5ZI13QCeS+RqSd93uuCqfvPG2/IqeLSO290oERJHhagwOOhb7Ml6yM1WT3R3zTMp7bv16EX9p9kk2paAJSRt90+PgptIzFCer/92om2RT+wgxSsa6bNPFd1jlLtNH+FjrudJvda2IC84GSoKuubChu+jxEO07vTAy36FWw6TZ+1zrP0MGrNra7kBglNjR4gbcGb77gEas1eRbnyDQ6Kvxkdz2EKS7DxPjMEk47ZA0Twstc9ySn83Vgl8TtJ2OfFGd0oazvNDceNfn700LdpLUHsJKBfrUbtzq7SGe3fnrilaTK2AJvfSAGCJh7VNY87nsBYsx6mrnA1RFZ0LGVxY6F+5Vw4uoxrBMGvDgehJeIUJxx17cQhS7hgKyvB7hX9Vm7/1t2aokeGaOKw==
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: keycloak
