apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-password
  namespace: keycloak
spec:
  encryptedData:
    password: AgBxDwcS5LiDjgcAUxcD1+hF4ZUubBWSgpesLmMzLsuFMybshN6VFU7Goucd1W+Jx8M9CECjmB2+nU8oWIVTMuXXO6qx3QRMis+X8JZacbsXkFc61m59t3f0aWRvGbSALAlGNV0r6ok4wBATNimZVD8LGhtJyBfoJn+FXNjDw4UyP5MAB+ooJuJpGvmfw0uyEA+XtdWn/XsMCEsOlFt+EDN7NynAkq2yT0HQ/eAW0mmd6ZTIAg6eNdQb481dkfEjJUdtbaWIIcI0IevpRZbwruhrjEofTcMLKqB/A9tCE51LaCVeNYjXZP0xt6B+00rkB9M98F7YxzNKttdXJtCgPiaOAid+F8Y6HC+wIn4yRf5HNmafDXvX2wcCrPVl2Lf4KnpAs7wDeUJDQgVLf1iMSWsrzX2/sbYSFrEE3MujizOYgeChSGH3skKRYbFV1aj0RxlnbLpzAPEU+ZsYx6XPA/dNccyBJZhXf+DhkQkUHq6P65MSCzovc5b8q5XBOkJDXPjvToVJY45rjDlQC51PQS+w//nMlwHfNs/0+ohb6gAE2K47x3e7zWmcZHTVMMFICexZYR9uRDpeSaMnZQg7HHXjO4v8klfS/2yNsMcvR1FQUo0iDoIZzcGD0uIjMLbctTeutwlAi/9b1SYl/skKFANmfUQ5OtlPHja7CLiOA/N3akl48hKKRgLJ9YyFh4wKzQww5O+/2aIhKZBTP0U=
  template:
    metadata:
      name: secrets
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgBSvomEJv/DkIrHbCusTNghNexgKsbq4u1AxT2ndwOz6EOq03EW55bclK+UmoC2jMQH/Fss6HyqtXNySVVwVrGUznSz23j3m+foPt6sA7xxBcRWiGoKNCxIg8dJ4rnci/Gn6oUqiQ1mxJdMc9/UpIejsEfCNB07oDpZAmVo7LVqo/Ry0NWLymZpfD1KCwVfJYUu7Jje+AznfvwqOXTuW/ppB6buGjjxp0vsqUpCRDemP78iJO7aXyD/LqmmqvyeZ80xybD4I8dknz5sz6sWHNFWUWdj7LI9FaMO0Qek31V2dzmsdKujJJLY2Y4AhoD5m4JlqDX1BoFqVzcUQyGgOsNVwucctLmS2IcZ/Ysjdkts3gHJUq2UMVyvY+vFEXGm2xHk/3t272iqD34GseIrVQgzmSBNImO97p+lml/fcAC/1S6CGoOQlMKYv5qTDBNEs/1Ld33x0/blARqRH+8uvAq5tWCrEkiJcpGQeFCt/+FCxd9GCAseou7duSdzhxJSs4ke79P5Ce/+A9P7SpeuWVOpYwLmtiQVHBu/Cb76wyM4u2j2Y+DtreD1TEvOZ5k9IUb2xEuo2xcvEvEQmnHEgnf3dfsumG1IlMs0aN5x37hLHzSsbY9SLxDmErjZ4xI3gKDV5hVHXwkthmtO7YEw9ZfrbpHXgQ81xUeU5AX9UX1YwKdzKvjx2Xfg5fcvIFU33UwW05m4DTd0OQ==
  template:
    metadata:
      name: secrets
      namespace: keycloak
