apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-password
  namespace: keycloak
spec:
  encryptedData:
    password: AgBWCJZeGIYyQASv4P14oQ9ULbW4fryKMaoNr0QiforBPCBRlwbUJZbVqvZ0FnZhpRVXgI6WHSU5wRbaJKBYeYlV2FSj27Qn7ESkVx/uGBOZCdE1IP07mYXYeCFhpkWhTlMIQ5eaTJ1yFGWG4hyn5SkYB8v5gqV73NW0cnGV7aDbrVXtFx6Q7W5k2Kt2vyawLfo8d6hbCv+04Mw35n5RwIadmBntvnHGsMz5DaZrPw7Ps4EmoXF0cHdWY4R+HJuGkooMRiF6Lvcn/PCEBIfYLE5migS6qRUCdD+z8YGmUNY9BD1H9gkQlIyEnEvaMKPCRGOITO9LVZYtRqkxTLYvodJGRA4SZ+zWwmYnUApcC3x74Q82swrGKtvdudhnsqlDf3wT49prrq/xWSbJU/334c7iztD9qzxqDKbYZkyt71sEuzmhRDvq4PQTGJXrXdGmh3mTNSfKI6g6n/TYPpiV/n2P6jTw1IgQcm3wZMLmKSB8CLznPk2aCCjWt1+40DkOP0Dg296hlEV8KzmRfoB1alYMbBOYcgbaZFeshh74c+ixlj89sU0O9g6zpG0xSGDqKeVSXG1rfBnvfcmq4SEDE0DMPVMjd8O21o949nBc+TnP+G3ahiOSEm9yKC0pt1E7AtxZPsQcAdFUUzjjXh+hrRc2nvV15edyR6aDfY5FQ34dQ1WBCAbtQBxBcTW4U9BwkmUHs4qsD4q61h/Se5o=
  template:
    metadata:
      name: postgres-password
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgBSvomEJv/DkIrHbCusTNghNexgKsbq4u1AxT2ndwOz6EOq03EW55bclK+UmoC2jMQH/Fss6HyqtXNySVVwVrGUznSz23j3m+foPt6sA7xxBcRWiGoKNCxIg8dJ4rnci/Gn6oUqiQ1mxJdMc9/UpIejsEfCNB07oDpZAmVo7LVqo/Ry0NWLymZpfD1KCwVfJYUu7Jje+AznfvwqOXTuW/ppB6buGjjxp0vsqUpCRDemP78iJO7aXyD/LqmmqvyeZ80xybD4I8dknz5sz6sWHNFWUWdj7LI9FaMO0Qek31V2dzmsdKujJJLY2Y4AhoD5m4JlqDX1BoFqVzcUQyGgOsNVwucctLmS2IcZ/Ysjdkts3gHJUq2UMVyvY+vFEXGm2xHk/3t272iqD34GseIrVQgzmSBNImO97p+lml/fcAC/1S6CGoOQlMKYv5qTDBNEs/1Ld33x0/blARqRH+8uvAq5tWCrEkiJcpGQeFCt/+FCxd9GCAseou7duSdzhxJSs4ke79P5Ce/+A9P7SpeuWVOpYwLmtiQVHBu/Cb76wyM4u2j2Y+DtreD1TEvOZ5k9IUb2xEuo2xcvEvEQmnHEgnf3dfsumG1IlMs0aN5x37hLHzSsbY9SLxDmErjZ4xI3gKDV5hVHXwkthmtO7YEw9ZfrbpHXgQ81xUeU5AX9UX1YwKdzKvjx2Xfg5fcvIFU33UwW05m4DTd0OQ==
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: keycloak
