apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graduation-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dan9191/infra.git
    targetRevision: main
    path: apps/graduation/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: graduation-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
