apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graduation-rag
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: rag-service=ghcr.io/dan9191/graduation-work/rag
    argocd-image-updater.argoproj.io/rag-service.update-strategy: digest
    argocd-image-updater.argoproj.io/rag-service.pull-secret: pullsecret:argocd/ghcr-secret
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/Dan9191/infra.git
    targetRevision: main
    path: apps/graduation/rag
  destination:
    server: https://kubernetes.default.svc
    namespace: graduation-rag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true