apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-dep
  namespace: graduation-rag
  labels:
    app: rag-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: rag-service
  template:
    metadata:
      labels:
        app: rag-service
    spec:
      containers:
        - name: rag-service
          image: ghcr.io/dan9191/graduation-work/rag:a631fe4d6157b3745caf9dcf784a33e03f89eff9
          imagePullPolicy: Always
          ports:
            - containerPort: 8094
              name: http
          envFrom:
            - configMapRef:
                name: graduation-rag-config
          env:
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass-secret
                  key: postgres-password
            - name: MODELS_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: models-token-secret
                  key:  models-token
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8094
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8094
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8094
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
