apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: graduation-rag
  namespace: argocd
spec:
  applications:
    - name: graduation-rag
      namespace: argocd

  images:
    - name: rag-service
      image: ghcr.io/dan9191/graduation-work/rag
      updateStrategy: digest
      allowTags:
        regexp: ^[0-9a-f]{40}$

  writeBack:
    method: git
    git:
      repository: https://github.com/Dan9191/infra.git
      branch: main
      credentials:
        secret:
          name: image-updater-git-cred
          namespace: argocd

  commitMessageTemplate: |
    chore: update image {{ .Image }} to {{ .NewTag }} (digest: {{ .NewDigest }})