---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: models-token-secret
  namespace: graduation-rag
spec:
  encryptedData:
    models-token: AgBRViLdSh0fKR3DaH9j1m3knblPwN+LOO8VVALOVtmMpFMbkpy/67idnugNLQnc1ZscIAC+2LlVWQR0WMpqW/aC5BaqagXdeJQAZEHfVD5XnjNWfarRgGTBp926DUvWv04M/LLlhPitFiqfcQS21Mp4HSnfYnyTLfv9Qhcn0bVGyNI4t1en7FPCnEhhCgbMvzBmbV3riRkxjlofOAm0+cAuaZWhghXJNuauCHgBJ8njQenaxnZUaFrNfkokZn1Hh6sOPF18cfW/v2Nf02oPmgawoOgFqO+itlB5P9Y/v7jzSHp/z1V8uYXTTe0liwaYVKXuO7ErR3uW3YyTm46Hz9bOYFfNDjxlxIgNvwVoL4Q5ze4l1Q4zUjKgOVzuV8ixVkLvi6OpG1N4Od3r1akzx64QskEq0pgHzskcfvXBcvFu60glvkm7K2KvvWlYZSqOWbopYCHQtRtTgFxYqFDYpkIIWAjD3cKFMqGVJZi6m5XrRMsdZ6xx0a/aoIU8IRzH5P0y9DRvdP5yJ0uFSijjHcuR+r/lpwrftyA6uV1B2oUIPScxIy03kRaqByQlWFO5JjmbR7QgtCJCqz/lfQNBbvPgniKRYvauSjlEY499C7qkn64EMP70jo4vQP2hbid6s9es1oeeS0y3A+fkhuxm2C4r6EK+YCjZmBS4AYqnbPEpAzmF55+gRXKk06SmdOex5q9qUPJqxQXZeWJueVjut/oDb3je2gafC7wlntm1OqeK5Qe1T0+mnbt582kkpoK8B0dGrla1GBSa2wris4beu6VxneNSSLtq4PQwh/lxPwiBL+TdVqITzvG7jMdhz9GaUg7KRalE
  template:
    metadata:
      name: models-token-secret
      namespace: graduation-rag
