---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-pass-secret
  namespace: graduation-rag
spec:
  encryptedData:
    postgres-password: AgBz89UrjRnVwTCRxdmDZL7MIJucWDOBcoWIuFMrcdonKpi1ohIB/rKXRTz+RbEXMUDU+zak3WeIYagHSoScrMj4eoay2j1f4f4Gl0qWAb6VwlzxSTCDlInHCx9AJDHyg0McqiTWgtdkeaa8J0vobN8w2pLJ5uLtHMVjTBiT3AUXOprz/yKhcYcwYrFDuX3h+zhTeFdNDCQ2lKnznIfD94VhqUrBf9UQ59q2sw8DSBuJ2/QAfvi+A6JOWAKKLGIVKgxGZTTSiaewAisHQTL4vTO9jy6DEgA6rsD8qQzQYN7+iTOiY3Bwzh/zvtgQnPvyYr7pumQ4eV7F2ox8Nd7QDAnpTTm5yx2RuibWey4DDd5P3OOkb2yGiUmEryhgKuBCvENyFQz8kMAtYgRDhym9CMGJsX32DDBif4bzu1PZx+gbMTN3wAUCzkFTaOfWNrfexkEIpffac7mK0oLpbnM5LzeDUSpAcpPKOMkMqitVbv5D/LTsseinkdOcJtjdgKEDIOydqNkycF/ifrRlzbK44wIlwpK4mtB5OxO8wVabvdmMMTnwknxiPEMlRfQMo7ZUE0RQe8odK+tjXi/HnQA758flWYmNlPISpd4KliXg115UisZvPFJtYEANnBWft4wcTlh7EykWGRyNGdAntDCBPD1/f7Cz4bUGhOCf2KjOMQZtaqz2O8MX+GgQuSNMzzlRgkYxvsetKXWBcLdV/2c=
  template:
    metadata:
      name: postgres-pass-secret
      namespace: graduation-rag
