---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgAaU3XjBaJSBL4YkRN6PzzzWYbrwLF7E+z0zrBPZjbLHWn3lMO5Gf8wjfl3jUSJ5eMwHqQ8uyObGqYndim5JspmJxmEg/1By/jFWi+nIDaKyCueULUh98qrt88dXXmunI3MfqSXMbB9YUIxKbgygQlPsEw4blahffz6rkF6kx6JiLSLG2IywIRkGpUgEcjziP5psRFtE5MCEXlUM7dmylnCNPgrt0AKKWXgCK6vwy0rMiAbHLJ4tf8tblecOtXdKRHtOR1KpUi2cxkQKlD7HLAAD3QHZMSJbjuBVaRx1kyVO9i3R4Z/X0Pg9Yun1zvu2z0mN2mh5XK2wqztOyHyS6x18VsrrxecHbsc4EXOwtgW9mmjZpPlUYjZoAmmUx9kNVJPrO4UDmtcD47g5ahhiv69fmxp8ZtQZVoVjdyakCaxyekOYwC6zxcHfUAFeBjVa3HBfg3zZyvJX4TxFCncUgptyMK5tpIZZT75TaZW/MZjaFd4L10LdAfJOAWfmbnp0Fu2E+W212kPi91DzH/8LdFPjXmtgSjTlebCB+QgpU3XEJcp3jrajWCC6yJRD3idGyiXWX+2opwTM8iPnKXysQPb4+UgiksYuK9r1NwlqqdCspwJeyc6VJcG2ORRotZOtl+MWks80ETkW9roZNie1SkWp3ogeQMKVLuJZKauvGgUY4mxVjF3dwYkB+Ao/yEJ/AvZHt8IQ3/VOcdVjMQ=
  template:
    metadata:
      name: postgres-secret
      namespace: postgres
