apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: gateway-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: graduation-gateway

  writeBackConfig:
    method: git
    git:
      credentials:
        secret:
          name: image-updater-git
          namespace: argocd

  images:
    - alias: gateway-service
      image: ghcr.io/dan9191/graduation-work/gateway
      updateStrategy: digest
      pullSecretRef:
        name: ghcr-secret
        namespace: argocd

  commit:
    messageTemplate: |
      chore(gateway): auto-update image digest

      [skip ci]
    author:
      name: argocd-image-updater
      email: argocd-image-updater@local

  interval: 1m