apiVersion: v1
kind: ConfigMap
metadata:
  name: graduation-article-config
  namespace: graduation-article
data:
  DATASOURCE_NAME: "postgres"
  DATASOURCE_R2DBC_URL: "r2dbc:postgresql://postgres.postgres.svc.cluster.local:5432/postgres?currentSchema=article_service"
  DATASOURCE_SCHEMAS: "article_service"
  DATASOURCE_URL: "jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/postgres"
  FLYWAY_LOCATIONS: "classpath:db/migration"
  KEYCLOAK: "https://auth.mos-hack.ru/realms/graduation"
  RABBITMQ_CON_TIMEOUT: "5000"
  RABBITMQ_EXCHANGE: "article.exchange"
  RABBITMQ_HOST: "rabbitmq.rabbitmq.svc.cluster.local"
  RABBITMQ_PASSWORD: "admin123"
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: "article.outbox.queue"
  RABBITMQ_ROUTING_KEY: "article.outbox"
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_VIRTUAL_HOST: "/"
  SERVER_PORT: "8093"
  SPRING_APPLICATION_NAME: "article-service"