---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-pass-secret
  namespace: graduation-article
spec:
  encryptedData:
    postgres-password: AgB5aRkl8cM/4PStfi2Y4q1ZOcHwOwKuN1XsyOTOXcaBvqV1Z0S5660XMnDveEnn3GukOeypmbHduH9VhNLgrxRfx0Iv75tV61F6h3SW8zthUFVtq/3rzIIKSmomVWnYTFBdqg1wNHePXEIyGMBPfTaqUriiDJW30G9wPozXEaJBcmGqYlETeB9RV3ox8e1YAjA90eNCsYn2kAj1dj5w+jO61bFWR0LlvDU6REnl75nN+1uHFNOOMSD0piBCemo5Uu1MHNBqJ6mPTegNtFoHK+pik10QDCvuPnc/I/KGVmyCqy7i5CjR15lhNNDsbwREFei9oFqPF65imaDhZlk/6bO0FeiDgSh1v4gU3XMcDczJ30O6DnW53MggLaJHUolBlKlMeEpkidzWFRAeE/EeRkeE8D9yZ6vXeNlSYQSN7RmQNNbtHF7SUmB5Yu5MUINXvqP9+pys5FUFbgwzfCHFaXih5sJej2EBb4CMInCaWsET/hFd9w6BY3ifQtgUcyzZWHavlS9xcUPfWLWfNJrfgwLisdM8vkMvfmnaR/YRXL+vPDsu1iomqjXCYMqo+RuaMtIA+IS/04H80Rm56U1nNwBgDLSOFMGsHFIto08DLyvSmvTfoRx0mEpDyxqq70VsFE03utYC2yavhu+YlBafAk45e82w8wbVv5WqaDHh/AID7Rf/uUhG8mz/J8nVYJdk2kHCxm6+8lH5nLZ3W3A=
  template:
    metadata:
      name: postgres-pass-secret
      namespace: graduation-article
