---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-pass-secret
  namespace: graduation-article
spec:
  encryptedData:
    postgres-password: AgB7ogOZXTlqIWUxv96sWJyqAZhK6UzPm2uRNGRFpV/alvg5mbeG/6ssw3bK2iNxQZHpPdiIpa1PbLv94DxsRjYh/L/LqC2MqG7kS+EPLYlfpt4AeMQeerWIODlbN4VwK23Nkra5ePmcPRIcu6QTI4dA078ymzbbWs68Cxj3eYMWMwffDxTvhyQlvgGUsdEC1oz1bZx3xLKzVvyyLQZ/QvUPBLo0XL2hBlNWqGfY7dtD7LZsqK4ZVnSlB/pAE52SGMk72mQSuMvUw7m987bNeEBTOxVZFrTCArzV1M+S9rr71fm6PIgJgv2NPGoYuFt+5fB/jnwUv01qAGxi94Y2l3FBYKKTaJtbYmqLcpNleWX/0FAW5SyK1rN8eWx9wblzimp6Rzt6yEVoOAFxzHAIJlz0SBXIp20wCgKaf7MBUoug7tB2ZaW0Y79QoTWtfv7GVzvDilyXGHKAuOnWGOakAlTXNhGqWxcibHt7mCuVHXlsnhQ4hGAmSfudUN/vbrOraNWaKBGsGHGNllILlsmQSSTDVDNc6o8F8MDPXenxovRAUmPRFSZzR+wZ8dvVuXt+o+HXZiatbejsijeIZ1va/5W8qsK6ORfSHVnuZYyfpn6WaUfl8ri5Pbo2MXkYN0cmuMpbHAaSXZvzBNYacaDceqAiyJLiT3dsIq1PWaaHCvUXCYfnKGd3w0HZrumcC73nfYQ/I5LEa3HYMJt5FUc=
  template:
    metadata:
      name: postgres-pass-secret
      namespace: graduation-article
