---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-pass-secret
  namespace: graduation-article
spec:
  encryptedData:
    postgres-password: AgAP8cOBivPXdB658I+ifZDmQW2r6QWPyWqKjIG9VznRiQ8ljY2CRjGFf+Ts84jm3rdvV1bJ2LbZTIomj+qyg29V8MnsrsmVhyFGU88PDfvasjw5m6bhYXm/cYGzIiBJMp1s8CRKJVrzxcbZvJKWszk5QF/hzg+3ARquyootSPflEd92bswq/STGDN+iSgSN23U4MSzI7GJjG05P8MaaYV/SpNPXKAbOU3d75JQ8MwXHqDWhhog/3ibqbIY7nyou84Xr/WhjUNgpmAKfE3/LVkxWMkSpe8dmwiVf18yJUcbvopGyQZob6mo36e1+TZe26BipvyFnHbCd/ImNvVNRnOOvr1MSQe/J4KW4wOY+iA9Lu7qocY5XobIyHl1O92U/q0wlS2aRL5y67APdHE/vZfpotc3gERyECqRg9nBuwh25gKTv+eh9OjXm8c1Ev6JGtyUXoCGAN2Zoi0gL7vSN1GNYnMN14Fl/H1d/IKx6T+KoUqIWwJgrcvfcYPenzsAIxAWgiE8D6tzcEzsI55O1Ycbv1jKfPpyHpzznrUSZWlD4JgFDKv7ge6GGAMKf+8mdybSMNWG6gsgSZIkXgG3XSqYJ78fleR7RoHGRJcd2SbDc5KIehclM+W0ydKIt9j9LKP1yXNjVx3beEu4JlxfD2pdvWoS/XFneGsdeGFNI48R/8IG0avtM7wILipx3+70TdKiDT7bK62lXEICl8hA=
  template:
    metadata:
      name: postgres-pass-secret
      namespace: graduation-article
