---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-updater-git
  namespace: argocd
spec:
  encryptedData:
    password: AgAGs04EIz014OFTy1IxLe53wA0SNsOneKkxDLmgC8NQlDTPRih5nyYme/j1miU6V7sojoiLosgTgwJAbV+PvBhejVT7I3MmHwNmYa2mS0P+RoFNpog3ayPswPZ3HDcaX99+IBlsy8eYVRkN346RpuWpzksFXwJx2iYvLqsV2WYWqIF5Tv9rCTN1xAea1/bZEWQy0GISiEPY9WtAwRHAjh6+XOXHGPg9AjFqkeCkXHEeFdsmv6w1dtEbnZgN9YtdBl7irwA+vXssQBRDZbnwhCNL10SxizrFSLSyXss8gFuTWcS7o/aqOny4Gc2g8CFrlWRJgZTl/yhuqGO4GDXgNxtrLXCJtyQ6eOAjd6FHfxA6Annl0yBMJOdlv3Nuitl7ToGA0lYZBRrXvJAQehaxQp/cxvFyc3t1KV6UrwkAWkldJwg0SwYm2cwt9dkAFlaiRT1rfcVakhFx8AOCBY94c9YK6ITu2hdPPg0GyRQEXawP+Owf6qAsAcEIswHEzmUEHvgPNnV/tyH74aBopGknOkOjfSbM/GVkU0KFc5fc3nvvqEiGqHr17Fbc6ZDipfJWL2aFeQdF3Dr5XK86SF9iMIK2NNStDEI/TToFkOx34uKbm509jmvGReNpkOk8MoOQBFzk52vdhAyP8rrayBgkbbRUHGRSFBff6yE89M9vP3IP5zKQt1Ds6xief9i7AGYh8iyXW9T20/VrJV3imSIFWbDUu3R9fgXt/TE7zh2zyntEG6SWU6BsmevK
    username: AgASY9F1Jtgm+WARXa+6ykq+OtxPnJuXwQ2Nbvz3fNIzb0NhtDEGPQyzn404ug+FyIR9FvH6vYHFtbuSasUz/o2uGrQ3TsRUjU+JIODCSAxtfqAT1BcNeLRpX4s9goMFKGPXAyLGnfb0joaAi+mZ6AJoJRsZPW5cvL08HABUVt+CVC7QGAMxst430KCMcrOhJVN7gzwCd8zCBUIfHPFs9zNK/hEvq6w2gTm/vtWIL+l2HoPj9MzEmGUJKn2wDwXuhgW//HWSbqfPoghXEezddxIR7F2dkdRJg8BBfiI1g1ojjFRFQSpJNr53LX0hqCEk+GeAlQixsNWVQ6DAkvNml+TPGo+xF2J+sY+51/fiF026sJoBCTCO93Fq5kWFgspbTL1PrCIitP7lY53JziM4wGSu9GtAZWsqtPFwAyqQxqQStjtMqVy/n3qm0ecFlu5mI2h4fV/iqkqSwS0/wHsbRxKvH8X+0X2ZfGbL+KOIOKdQyFinwEv9SkvZPo4cMXUGt96yQByFKdzFHt8i3DdWFtLdzEqQnL1Gvjq7Ix638hxycR2F8QAnl1+tRps9ezb2kTd8x4euct6pUjhwxQEmkrjpevsjvggZKgScAaHSUY4VQ3X5d9elXMrMezszb4scjvDVAHuXC4umoR0l9x5Bt92UOE8WWc15/FUDN4L6ACq9rdAIDKQ6J9OzsgR9w87PzEyUaoIC0AF2
  template:
    metadata:
      name: image-updater-git
      namespace: argocd
