---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBBpazkydHYwEHWeTmu2NDfm0NrM6RUWDp3i/BT6WoLSRqs/TQ9HgjaAL0LYaUEGqs0QUupCrSdRZJvAHQ5YRzGJNfbYfE+JgEgSCA7ZrU9E98tX2VCUd2taLgPPXEAUaCC+N7RhY0h+SkfvHcVoSK57aXyAz55xUJhk4JCln/LsRZKGxN1cCAKvZ33Cu1isaE6fPopbkeCVbZs7GxA7eNPm9AT0avQLc5JhSNhvSLt4irEuQD3ondxF/0U06zDpsoCZr5TD+w/Xrsxu2ZUM1ybMhLl7SCGTrXrtJCvm4SBLfk8SIXQFvSCru8NyDXDrlpXP/LlE1FuqJFZ+9tyAAtBb1v09q65uCOCjbKTi9tHgitG8wR1sNpg9BSdPLCfl2O0Ichiv/nCriWKlZ+Uyg3xB1l5rVIwQ+P8HB4jmM943K+ptMG6hG/ezqiQye2j7lKcKZg9hn2dehDPpZev7KGHbA/Wg48kbFEY/98r0j6WfqnxGTsuD/g/zFZ6wU7YEFwlA5CKHltGAJWyfCt/5CpaCPHUXiBIeOkND+dCeZenh+xYPY6GORrFbQwMUL0p+uuFTM1HhzwQh6dWFA6EUBQmjIBldoyLDREZ4hLv1iloF5epcOs3fgnRfaWSTxBbnrCgHIJyGsG1C4ydRryC5N9slT6+LCSXl7n6WRKIEaS0x6nr0j9EgT0447hJSRSS9qNqYT5TtmSpXrmqHO6YQ+mbiyPiaDsov7oO0hp7dfsMwrYgZIAqPbCOpOF5Br/hMQcHLtm3umVcAw4MPY/KXfX3j9I6ZWUN/c0OHHQfv/EHylDa2/9v51LRJSGJTTUAQ2dc8Fu6dNFMFdSFIAZhIod5VeFX3SuhYGDDK/PUvMlpTJZ6PZkpuZRQIOEWZX4zYtEMLRldTiXqYW1Nvj+g9iHfRrETT/FDCtve5tSN
  template:
    metadata:
      name: ghcr-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
