---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBIUu3cNJQ4RYXBi3iMielcEirht+4ddX0vcHkOjjURndkYfkuBOgYocVx7AQhdFWF5sEMoyFXxZYqYA7U/+3BB5OOG9NOVGre+OBZX7ufUlchVHCUG9rfzId0MsAK3sX+1iNo7Q16wCrClf9LjMtB4wLTu8RxjcqVikQKIVEzQ5QhxjXUin+4hMHirF42bgABfULE6GRRs17Q7LP7j0t7bmV5OBhziNPRFE9Ouq6fnIkXiidh/9iUB75EByMnf56fd0rNlFpWynSCs110yQmgMOx2HEzy2gEPrFm/l07ywyyCsnveHOBTrZQeAxvjqUzttq+KEWS9QyHlVDI2k+1yUO3wGzKGgBq6sQqi4T2tiz5T7z2fzOBjlJan/WcXFZ/Bdp9pV7QUF36lBSrpUeDF+2YhsLF2oiB8NKn/wyaJjhLby8gp0bofs9k88Os8mpsfpvZ+lmMwv7Dw5+iICTimDzc4Visc0Ixx0lgFYQxk6AfaLloWQsbA1K8SOoLryjQ/5ID2jzLcQX3i9pEB5bVcz//tT6OHwwKp+2AqYTS0FDTzN3gKtPNlW6ph0buiMzabNx3dbhuMXQ7NFqrZohQbaaa4/C8W8nIMiA0POR2MKdPZiMR1p91uq180Ell1JnHviOyQBQu+Zaz258QzUfepWwW26P4/ojboi+49ia+38Czd/f1dJopBaUO7ZkHsl7SG85bVNajuIvAUmMIQ+esf5Whupz0CeeJI+pziocwwxyxUU3x0kLMyp7dFCPoXubb4C90w+ChJTJ0MDTnhWW1yY/3CxkdCBSm1pqrDzocA8DxsIUTMr4ixQElkOUta5saldN31G7zj2i32rQXCA9rqOuQ3KBhL2vtH8
  template:
    metadata:
      name: ghcr-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
